**DS 301: Applied Data Modeling and Predictive Analysis**

**Lecture 3 – System Setup**

# Logistic Regression with scikit-learn
Nok Wongpiromsarn, 8 August 2022

We begin by importing the packages and modules that we will need.

In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

**Set up the data**

In [2]:
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array([2, 12, 30, 56, 90])

**Split the data into training and test sets**

In [3]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=2)
print("Training set:\n" + str(np.c_[x_train, y_train]))
print("Testing set:\n" + str(np.c_[x_test, y_test]))

Training set:
[[ 3  4 12]
 [ 7  8 56]
 [ 1  2  2]]
Testing set:
[[ 5  6 30]
 [ 9 10 90]]


**Train the model on the training set**

In [4]:
clf = LogisticRegression().fit(x_train, y_train)

**Make predictions on the test set**

In [5]:
y_pred = clf.predict(x_test)
print(y_pred)

[56 56]


**Compute the fraction of correctly classified samples in the test set**

In [6]:
print(metrics.accuracy_score(y_test, y_pred))
print(clf.score(x_test, y_test))

0.0
0.0
